=== policy4j/xacml4j/first_repo/xacml-conformance-tests/src/test/resources/Example_2/record.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:med:example:schemas:record" xmlns:rec="urn:med:example:schemas:record" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="record" type="rec:RecordType"/>
	<xs:complexType name="RecordType">
		<xs:sequence>
			<xs:element name="patient" type="rec:PatientType"/>
			<xs:element name="parentGuardian" type="rec:ParentGuardianType" minOccurs="0" maxOccurs="2"/>
			<xs:element name="primaryCarePhysician" type="rec:PhysicianType" minOccurs="0"/>
			<xs:element name="insurer" type="rec:CompanyType"/>
			<xs:element name="medical" type="rec:MedicalType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PatientType">
		<xs:sequence>
			<xs:element name="patientName" type="rec:NameType"/>
			<xs:element name="patientContact" type="rec:ContactType"/>
			<xs:element name="patientDoB" type="xs:date"/>
			<xs:element name="patientGender" type="rec:GenderType"/>
			<xs:element name="policyNumber" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="GenderType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="male"/>
			<xs:enumeration value="female"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ParentGuardianType">
		<xs:sequence>
			<xs:element name="parentGuardianName" type="rec:NameType"/>
			<xs:element name="parentGuardianContact" type="rec:ContactType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PhysicianType">
		<xs:sequence>
			<xs:element name="physicianName" type="rec:NameType"/>
			<xs:element name="physicianContact" type="rec:ContactType"/>
			<xs:element name="registrationID" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CompanyType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="street" type="xs:string"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="state" type="xs:string"/>
			<xs:element name="zip" type="xs:string"/>
			<xs:element name="phone" type="xs:string"/>
			<xs:element name="fax" type="xs:string"/>
			<xs:element name="email" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NameType">
		<xs:sequence>
			<xs:element name="first" type="xs:string"/>
			<xs:element name="last" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ContactType">
		<xs:sequence>
			<xs:element name="street" type="xs:string"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="state" type="xs:string"/>
			<xs:element name="zip" type="xs:string"/>
			<xs:element name="phone" type="xs:string"/>
			<xs:element name="fax" type="xs:string" minOccurs="0"/>
			<xs:element name="email" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MedicalType">
		<xs:sequence>
			<xs:element name="treatment" type="rec:TreatmentType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="result" type="rec:ResultType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TreatmentType">
		<xs:sequence>
			<xs:element name="drug" type="rec:DrugType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="comment" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ResultType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="test" type="xs:string"/>
			<xs:element name="value" type="xs:string"/>
			<xs:element name="date" type="xs:date"/>
			<xs:element name="performedBy" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DrugType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="dailyDosage" type="xs:string"/>
			<xs:element name="startDate" type="xs:date"/>
			<xs:element name="stopDate" type="xs:date" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== policy4j/xacml4j/first_repo/xacml-conformance-tests/src/test/resources/Example_2/Barts_record.xml
<?xml version="1.0" encoding="UTF-8"?>
<record xmlns="urn:med:example:schemas:record" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:med:example:schemas:record record.xsd">
	<patient>
		<patientName>
			<first>Bartholomew</first>
			<last>Simpson</last>
		</patientName>
		<patientContact>
			<street>27 Shelbyville Road</street>
			<city>Springfield</city>
			<state>MA</state>
			<zip>12345</zip>
			<phone>555.123.4567</phone>
			<fax/>
			<email/>
		</patientContact>
		<patientDoB>1992-03-21</patientDoB>
		<patientGender>male</patientGender>
		<policyNumber>555555</policyNumber>
	</patient>
	<parentGuardian>
		<parentGuardianName>
			<first>Homer</first>
			<last>Simpson</last>
		</parentGuardianName>
		<parentGuardianContact>
			<street>27 Shelbyville Road</street>
			<city>Springfield</city>
			<state>MA</state>
			<zip>12345</zip>
			<phone>555.123.4567</phone>
			<fax/>
			<email>homers@aol.com</email>
		</parentGuardianContact>
	</parentGuardian>
	<primaryCarePhysician>
		<physicianName>
			<first>Julius</first>
			<last>Hibbert</last>
		</physicianName>
		<physicianContact>
			<street>1 First St</street>
			<city>Springfield</city>
			<state>MA</state>
			<zip>12345</zip>
			<phone>555.123.9012</phone>
			<fax>555.123.9013</fax>
			<email/>
		</physicianContact>
		<registrationID>ABC123</registrationID>
	</primaryCarePhysician>
	<insurer>
		<name>Blue Cross</name>
		<street>1234 Main St</street>
		<city>Springfield</city>
		<state>MA</state>
		<zip>12345</zip>
		<phone>555.123.5678</phone>
		<fax>555.123.5679</fax>
		<email/>
	</insurer>
	<medical>
		<treatment>
			<drug>
				<name>methylphenidate hydrochloride</name>
				<dailyDosage>30mgs</dailyDosage>
				<startDate>1999-01-12</startDate>
			</drug>
			<comment>patient exhibits side-effects of skin coloration and carpal degeneration</comment>
		</treatment>
		<result>
			<test>blood pressure</test>
			<value>120/80</value>
			<date>2001-06-09</date>
			<performedBy>Nurse Betty</performedBy>
		</result>
	</medical>
</record>
